apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: upgrader-rb
  namespace: redhat-ods-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: upgrader-role
subjects:
- kind: ServiceAccount
  name: upgrader-sa
  apiGroup: ""